<?php
/**
 * ReportsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Mintsoft;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ReportsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReportsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation reportsCourierDespatchReport
     *
     * Courier Despatch Report
     *
     * @param  \DateTime $despatch_date_start Despatch Start Date (required)
     * @param  \DateTime $despatch_date_end Despatch End Date (required)
     * @param  int $courier_id Optional - Filter the results by Courier (optional)
     * @param  int $warehouse_id Optional - Filter the results by Warehouse (optional)
     * @param  bool $breakdown_by_country Optional - Breakdown the results on Per Country Basis (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\MintsoftReportsCourierDespatchReportLine[]
     */
    public function reportsCourierDespatchReport($despatch_date_start, $despatch_date_end, $courier_id = null, $warehouse_id = null, $breakdown_by_country = null)
    {
        list($response) = $this->reportsCourierDespatchReportWithHttpInfo($despatch_date_start, $despatch_date_end, $courier_id, $warehouse_id, $breakdown_by_country);
        return $response;
    }

    /**
     * Operation reportsCourierDespatchReportWithHttpInfo
     *
     * Courier Despatch Report
     *
     * @param  \DateTime $despatch_date_start Despatch Start Date (required)
     * @param  \DateTime $despatch_date_end Despatch End Date (required)
     * @param  int $courier_id Optional - Filter the results by Courier (optional)
     * @param  int $warehouse_id Optional - Filter the results by Warehouse (optional)
     * @param  bool $breakdown_by_country Optional - Breakdown the results on Per Country Basis (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\MintsoftReportsCourierDespatchReportLine[], HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsCourierDespatchReportWithHttpInfo($despatch_date_start, $despatch_date_end, $courier_id = null, $warehouse_id = null, $breakdown_by_country = null)
    {
        $returnType = '\Swagger\Client\Model\MintsoftReportsCourierDespatchReportLine[]';
        $request = $this->reportsCourierDespatchReportRequest($despatch_date_start, $despatch_date_end, $courier_id, $warehouse_id, $breakdown_by_country);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\MintsoftReportsCourierDespatchReportLine[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation reportsCourierDespatchReportAsync
     *
     * Courier Despatch Report
     *
     * @param  \DateTime $despatch_date_start Despatch Start Date (required)
     * @param  \DateTime $despatch_date_end Despatch End Date (required)
     * @param  int $courier_id Optional - Filter the results by Courier (optional)
     * @param  int $warehouse_id Optional - Filter the results by Warehouse (optional)
     * @param  bool $breakdown_by_country Optional - Breakdown the results on Per Country Basis (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reportsCourierDespatchReportAsync($despatch_date_start, $despatch_date_end, $courier_id = null, $warehouse_id = null, $breakdown_by_country = null)
    {
        return $this->reportsCourierDespatchReportAsyncWithHttpInfo($despatch_date_start, $despatch_date_end, $courier_id, $warehouse_id, $breakdown_by_country)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation reportsCourierDespatchReportAsyncWithHttpInfo
     *
     * Courier Despatch Report
     *
     * @param  \DateTime $despatch_date_start Despatch Start Date (required)
     * @param  \DateTime $despatch_date_end Despatch End Date (required)
     * @param  int $courier_id Optional - Filter the results by Courier (optional)
     * @param  int $warehouse_id Optional - Filter the results by Warehouse (optional)
     * @param  bool $breakdown_by_country Optional - Breakdown the results on Per Country Basis (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reportsCourierDespatchReportAsyncWithHttpInfo($despatch_date_start, $despatch_date_end, $courier_id = null, $warehouse_id = null, $breakdown_by_country = null)
    {
        $returnType = '\Swagger\Client\Model\MintsoftReportsCourierDespatchReportLine[]';
        $request = $this->reportsCourierDespatchReportRequest($despatch_date_start, $despatch_date_end, $courier_id, $warehouse_id, $breakdown_by_country);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'reportsCourierDespatchReport'
     *
     * @param  \DateTime $despatch_date_start Despatch Start Date (required)
     * @param  \DateTime $despatch_date_end Despatch End Date (required)
     * @param  int $courier_id Optional - Filter the results by Courier (optional)
     * @param  int $warehouse_id Optional - Filter the results by Warehouse (optional)
     * @param  bool $breakdown_by_country Optional - Breakdown the results on Per Country Basis (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function reportsCourierDespatchReportRequest($despatch_date_start, $despatch_date_end, $courier_id = null, $warehouse_id = null, $breakdown_by_country = null)
    {
        // verify the required parameter 'despatch_date_start' is set
        if ($despatch_date_start === null || (is_array($despatch_date_start) && count($despatch_date_start) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $despatch_date_start when calling reportsCourierDespatchReport'
            );
        }
        // verify the required parameter 'despatch_date_end' is set
        if ($despatch_date_end === null || (is_array($despatch_date_end) && count($despatch_date_end) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $despatch_date_end when calling reportsCourierDespatchReport'
            );
        }

        $resourcePath = '/api/Reports/CourierDespatchReport';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($despatch_date_start !== null) {
            $queryParams['DespatchDateStart'] = ObjectSerializer::toQueryValue($despatch_date_start);
        }
        // query params
        if ($despatch_date_end !== null) {
            $queryParams['DespatchDateEnd'] = ObjectSerializer::toQueryValue($despatch_date_end);
        }
        // query params
        if ($courier_id !== null) {
            $queryParams['CourierId'] = ObjectSerializer::toQueryValue($courier_id);
        }
        // query params
        if ($warehouse_id !== null) {
            $queryParams['WarehouseId'] = ObjectSerializer::toQueryValue($warehouse_id);
        }
        // query params
        if ($breakdown_by_country !== null) {
            $queryParams['BreakdownByCountry'] = ObjectSerializer::toQueryValue($breakdown_by_country);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'ab');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
