<?php
/**
 * ToolkitDataClassesReturnsReturnTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesReturnsReturnTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesReturnsReturn
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesReturnsReturnTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesReturnsReturn"
     */
    public function testToolkitDataClassesReturnsReturn()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "advanced_external_return"
     */
    public function testPropertyAdvancedExternalReturn()
    {
    }

    /**
     * Test attribute "confirmed"
     */
    public function testPropertyConfirmed()
    {
    }

    /**
     * Test attribute "exchanged"
     */
    public function testPropertyExchanged()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "exchanged_order_id"
     */
    public function testPropertyExchangedOrderId()
    {
    }

    /**
     * Test attribute "invoiced"
     */
    public function testPropertyInvoiced()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "return_items"
     */
    public function testPropertyReturnItems()
    {
    }

    /**
     * Test attribute "return_name_values"
     */
    public function testPropertyReturnNameValues()
    {
    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
