<?php
/**
 * ToolkitDataClassesClientsClientTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesClientsClientTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesClientsClient
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesClientsClientTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesClientsClient"
     */
    public function testToolkitDataClassesClientsClient()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "brand_name"
     */
    public function testPropertyBrandName()
    {
    }

    /**
     * Test attribute "contact_name"
     */
    public function testPropertyContactName()
    {
    }

    /**
     * Test attribute "contact_number"
     */
    public function testPropertyContactNumber()
    {
    }

    /**
     * Test attribute "address_line1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "address_line2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "address_line3"
     */
    public function testPropertyAddressLine3()
    {
    }

    /**
     * Test attribute "town"
     */
    public function testPropertyTown()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "ppi_number"
     */
    public function testPropertyPpiNumber()
    {
    }

    /**
     * Test attribute "vat_number"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "eori_number"
     */
    public function testPropertyEoriNumber()
    {
    }

    /**
     * Test attribute "ukims_number"
     */
    public function testPropertyUkimsNumber()
    {
    }

    /**
     * Test attribute "voec_number"
     */
    public function testPropertyVoecNumber()
    {
    }

    /**
     * Test attribute "vat_exempt"
     */
    public function testPropertyVatExempt()
    {
    }

    /**
     * Test attribute "nireori_number"
     */
    public function testPropertyNireoriNumber()
    {
    }

    /**
     * Test attribute "ioss_number"
     */
    public function testPropertyIossNumber()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "contact_email"
     */
    public function testPropertyContactEmail()
    {
    }

    /**
     * Test attribute "packaging_instructions"
     */
    public function testPropertyPackagingInstructions()
    {
    }

    /**
     * Test attribute "currency_id"
     */
    public function testPropertyCurrencyId()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "on_stop"
     */
    public function testPropertyOnStop()
    {
    }

    /**
     * Test attribute "accounting_integration_type"
     */
    public function testPropertyAccountingIntegrationType()
    {
    }

    /**
     * Test attribute "customer_registration_number"
     */
    public function testPropertyCustomerRegistrationNumber()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
