<?php
/**
 * ToolkitDataClassesStockStockFlowTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesStockStockFlowTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesStockStockFlow
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesStockStockFlowTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesStockStockFlow"
     */
    public function testToolkitDataClassesStockStockFlow()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "warehouse_id"
     */
    public function testPropertyWarehouseId()
    {
    }

    /**
     * Test attribute "stock_level"
     */
    public function testPropertyStockLevel()
    {
    }

    /**
     * Test attribute "allocated"
     */
    public function testPropertyAllocated()
    {
    }

    /**
     * Test attribute "on_hand"
     */
    public function testPropertyOnHand()
    {
    }

    /**
     * Test attribute "off_hand"
     */
    public function testPropertyOffHand()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "flow"
     */
    public function testPropertyFlow()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "best_before"
     */
    public function testPropertyBestBefore()
    {
    }

    /**
     * Test attribute "batch_no"
     */
    public function testPropertyBatchNo()
    {
    }

    /**
     * Test attribute "serial_no"
     */
    public function testPropertySerialNo()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "storage_item_id"
     */
    public function testPropertyStorageItemId()
    {
    }

    /**
     * Test attribute "parent_storage_item_id"
     */
    public function testPropertyParentStorageItemId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "stock_flow_details"
     */
    public function testPropertyStockFlowDetails()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "warehouse_name"
     */
    public function testPropertyWarehouseName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
