<?php
/**
 * ToolkitDataClassesOrdersOrderShipmentTrackingEventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesOrdersOrderShipmentTrackingEventTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesOrdersOrderShipmentTrackingEvent
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesOrdersOrderShipmentTrackingEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesOrdersOrderShipmentTrackingEvent"
     */
    public function testToolkitDataClassesOrdersOrderShipmentTrackingEvent()
    {
    }

    /**
     * Test attribute "order_shipment_id"
     */
    public function testPropertyOrderShipmentId()
    {
    }

    /**
     * Test attribute "order_shipment"
     */
    public function testPropertyOrderShipment()
    {
    }

    /**
     * Test attribute "tracking_status_id"
     */
    public function testPropertyTrackingStatusId()
    {
    }

    /**
     * Test attribute "courier_customer_description"
     */
    public function testPropertyCourierCustomerDescription()
    {
    }

    /**
     * Test attribute "courier_external_description"
     */
    public function testPropertyCourierExternalDescription()
    {
    }

    /**
     * Test attribute "courier_tracking_stage_code"
     */
    public function testPropertyCourierTrackingStageCode()
    {
    }

    /**
     * Test attribute "courier_tracking_event_id"
     */
    public function testPropertyCourierTrackingEventId()
    {
    }

    /**
     * Test attribute "courier_time_stamp"
     */
    public function testPropertyCourierTimeStamp()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
