<?php
/**
 * ToolkitDataClassesStockProductPurchasingSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesStockProductPurchasingSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesStockProductPurchasingSettings
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesStockProductPurchasingSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesStockProductPurchasingSettings"
     */
    public function testToolkitDataClassesStockProductPurchasingSettings()
    {
    }

    /**
     * Test attribute "default_min_order_qty"
     */
    public function testPropertyDefaultMinOrderQty()
    {
    }

    /**
     * Test attribute "default_max_order_qty"
     */
    public function testPropertyDefaultMaxOrderQty()
    {
    }

    /**
     * Test attribute "default_order_qty"
     */
    public function testPropertyDefaultOrderQty()
    {
    }

    /**
     * Test attribute "include_linked_items"
     */
    public function testPropertyIncludeLinkedItems()
    {
    }

    /**
     * Test attribute "exclude_from_forecast"
     */
    public function testPropertyExcludeFromForecast()
    {
    }

    /**
     * Test attribute "forecast_period_days"
     */
    public function testPropertyForecastPeriodDays()
    {
    }

    /**
     * Test attribute "lead_time_days"
     */
    public function testPropertyLeadTimeDays()
    {
    }

    /**
     * Test attribute "avg_daily_consumption"
     */
    public function testPropertyAvgDailyConsumption()
    {
    }
}
