<?php
/**
 * ToolkitDataClassesAccountGoodsInInvoiceItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesAccountGoodsInInvoiceItemTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesAccountGoodsInInvoiceItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesAccountGoodsInInvoiceItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesAccountGoodsInInvoiceItem"
     */
    public function testToolkitDataClassesAccountGoodsInInvoiceItem()
    {
    }

    /**
     * Test attribute "invoice_summary_id"
     */
    public function testPropertyInvoiceSummaryId()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "asnid"
     */
    public function testPropertyAsnid()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "delivery_size_cost"
     */
    public function testPropertyDeliverySizeCost()
    {
    }

    /**
     * Test attribute "number_of_units"
     */
    public function testPropertyNumberOfUnits()
    {
    }

    /**
     * Test attribute "unit_cost"
     */
    public function testPropertyUnitCost()
    {
    }

    /**
     * Test attribute "admin_cost"
     */
    public function testPropertyAdminCost()
    {
    }

    /**
     * Test attribute "total_unit_cost"
     */
    public function testPropertyTotalUnitCost()
    {
    }

    /**
     * Test attribute "number_of_skus"
     */
    public function testPropertyNumberOfSkus()
    {
    }

    /**
     * Test attribute "sku_cost"
     */
    public function testPropertySkuCost()
    {
    }

    /**
     * Test attribute "total_per_sku_cost"
     */
    public function testPropertyTotalPerSkuCost()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
