<?php
/**
 * ToolkitDataClassesOrdersBarcodeVerifiedOrderItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesOrdersBarcodeVerifiedOrderItemTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesOrdersBarcodeVerifiedOrderItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesOrdersBarcodeVerifiedOrderItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesOrdersBarcodeVerifiedOrderItem"
     */
    public function testToolkitDataClassesOrdersBarcodeVerifiedOrderItem()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "product_in_location_id"
     */
    public function testPropertyProductInLocationId()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "manually_confirmed"
     */
    public function testPropertyManuallyConfirmed()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "batch_no"
     */
    public function testPropertyBatchNo()
    {
    }

    /**
     * Test attribute "serial_no"
     */
    public function testPropertySerialNo()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "mobile_app"
     */
    public function testPropertyMobileApp()
    {
    }

    /**
     * Test attribute "box_number"
     */
    public function testPropertyBoxNumber()
    {
    }

    /**
     * Test attribute "sscc_number"
     */
    public function testPropertySsccNumber()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {
    }

    /**
     * Test attribute "last_updated_by_user"
     */
    public function testPropertyLastUpdatedByUser()
    {
    }
}
