<?php
/**
 * ToolkitDataClassesReportsCourierDespatchReportLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesReportsCourierDespatchReportLineTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesReportsCourierDespatchReportLine
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesReportsCourierDespatchReportLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesReportsCourierDespatchReportLine"
     */
    public function testToolkitDataClassesReportsCourierDespatchReportLine()
    {
    }

    /**
     * Test attribute "courier_service"
     */
    public function testPropertyCourierService()
    {
    }

    /**
     * Test attribute "no_of_parcels"
     */
    public function testPropertyNoOfParcels()
    {
    }

    /**
     * Test attribute "total_weight"
     */
    public function testPropertyTotalWeight()
    {
    }

    /**
     * Test attribute "ppi_logo_id"
     */
    public function testPropertyPpiLogoId()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {
    }

    /**
     * Test attribute "average_weight"
     */
    public function testPropertyAverageWeight()
    {
    }
}
