<?php
/**
 * ToolkitDataClassesWarehouseBookStockRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesWarehouseBookStockRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesWarehouseBookStockRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesWarehouseBookStockRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesWarehouseBookStockRequest"
     */
    public function testToolkitDataClassesWarehouseBookStockRequest()
    {
    }

    /**
     * Test attribute "oms_version"
     */
    public function testPropertyOmsVersion()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "warehouse_id"
     */
    public function testPropertyWarehouseId()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "adjustment"
     */
    public function testPropertyAdjustment()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "asnid"
     */
    public function testPropertyAsnid()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "batch_no"
     */
    public function testPropertyBatchNo()
    {
    }

    /**
     * Test attribute "serial_no"
     */
    public function testPropertySerialNo()
    {
    }

    /**
     * Test attribute "destination_warehouse_id"
     */
    public function testPropertyDestinationWarehouseId()
    {
    }

    /**
     * Test attribute "destination_location_id"
     */
    public function testPropertyDestinationLocationId()
    {
    }

    /**
     * Test attribute "kit_id"
     */
    public function testPropertyKitId()
    {
    }
}
