<?php
/**
 * ToolkitDataClassesWarehouseAPIWarehouseTransferItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ToolkitDataClassesWarehouseAPIWarehouseTransferItemTest Class Doc Comment
 *
 * @category    Class
 * @description ToolkitDataClassesWarehouseAPIWarehouseTransferItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToolkitDataClassesWarehouseAPIWarehouseTransferItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ToolkitDataClassesWarehouseAPIWarehouseTransferItem"
     */
    public function testToolkitDataClassesWarehouseAPIWarehouseTransferItem()
    {
    }

    /**
     * Test attribute "warehouse_transfer_id"
     */
    public function testPropertyWarehouseTransferId()
    {
    }

    /**
     * Test attribute "warehouse_transfer"
     */
    public function testPropertyWarehouseTransfer()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "complete"
     */
    public function testPropertyComplete()
    {
    }
}
