<?php
/**
 * ReturnApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.47-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ReturnApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for returnAddReturnItem
     *
     * .
     *
     */
    public function testReturnAddReturnItem()
    {
    }

    /**
     * Test case for returnAllocateItemLocation
     *
     * .
     *
     */
    public function testReturnAllocateItemLocation()
    {
    }

    /**
     * Test case for returnConfirmReturn
     *
     * .
     *
     */
    public function testReturnConfirmReturn()
    {
    }

    /**
     * Test case for returnCreateReturn
     *
     * .
     *
     */
    public function testReturnCreateReturn()
    {
    }

    /**
     * Test case for returnGetReturn
     *
     * .
     *
     */
    public function testReturnGetReturn()
    {
    }

    /**
     * Test case for returnGetReturnItems
     *
     * .
     *
     */
    public function testReturnGetReturnItems()
    {
    }

    /**
     * Test case for returnGetReturnReasons
     *
     * .
     *
     */
    public function testReturnGetReturnReasons()
    {
    }

    /**
     * Test case for returnGetReturnsOnDate
     *
     * .
     *
     */
    public function testReturnGetReturnsOnDate()
    {
    }
}
